name: Publish Package on NPM

on:
    workflow_run:
        workflows: ['Run Tests']
        types:
            - completed

jobs:
    publish:
        runs-on: ubuntu-latest
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'main'
        steps:
            - name: Setup bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Clean install dependencies
              run: |
                  bun i

            - name: Build
              run: |
                  bun run build

            - name: Publish
              run: |
                  bun run publish

            - name: Publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
